apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::814530570635:user/github-actions-user
      username: github-actions-user
      groups:
        - system:masters