apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-builder-deployment
  labels:
    app: cv-builder-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-builder-api
  template:
    metadata:
      labels:
        app: cv-builder-api
    spec:
      containers:
        - name: cv-builder-api
          image: 814530570635.dkr.ecr.eu-west-1.amazonaws.com/dev-ecr-repo-1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080